### ISSUE TITLE
Tag issue at templates with django 1.6

### ISSUE THREAD

**Issue by cbanicolas** [tkaemming/django-subdomains#27]
Hi, i have a problem in the templates for creating the urls. for example:

<a href="{% url 'lista' 'subdomain' cat_slug=categoria.slug %}">

And the error received:
Don't mix *args and **kwargs in call to reverse()!

I tried the other tags to but no one works, {% load subdomainurls %} gives me the following error:

'subdomainurls' is not a valid tag library: Template library subdomainurls not found, tried django.templatetags.subdomainurls,django.contrib.admin.templatetags.subdomainurls,django.contrib.staticfiles.templatetags.subdomainurls

Any ideas ??? i tried adding this in settings:

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.core.context_processors.request' #PARA PODER USAR DJANGO-SUBDOMAINS EN LOS TEMPLATES
)

but it didn't work.

Thanks alot !

**Comment by tkaemming** [comment]
The above comment is correct, there are also more details here: https://github.com/tkaemming/django-subdomains/blob/master/docs/index.rst#quick-start
