### ISSUE TITLE
dict.iteritems() are no longer supported in Python 3.0

### ISSUE THREAD

**Issue by markhaasjes** [tkaemming/django-subdomains#30]
The dict.iterkeys(), dict.iteritems() and dict.itervalues() methods are no longer supported in Python 3.0.
Instead use dict.keys(), dict.items() and dict.values().
https://docs.python.org/release/3.0.1/whatsnew/3.0.html#views-and-iterators-instead-of-lists

**Comment by tkaemming** [comment]
This should be resolved as of 5c501edcbc28d1e42c8a928a783066519eba6a31, tests now include Python 3.4 and 3.5 where applicable also.

This isn't on PyPI yet, but probably will be sometime this week or next.
