### ISSUE TITLE
how do i test my subdomains when using runserver on localhost during development?

### ISSUE THREAD

**Issue by ShubhamBadal** [tkaemming/django-subdomains#39]
how to use subdomains in localhost python runserver

**Comment by vaibhav-jain** [comment]
@ShubhamBadal  can you tell me exactly how did you make this work on dev machine. I want to route urls based on subdomain too...

**Comment by vaibhav-jain** [comment]
@ShubhamBadal  please close this issue if it is resolved...

**Comment by ShubhamBadal** [comment]
@vaibhav-jain i configured by makin guse of hexxie.com
read more at http://www.seanbehan.com/setup-wildcard-subdomain-on-localhost-for-development-work-without-etchosts-tomfoolery

Issue was solved by using this hack, but i dont think there is any other way inbuilt in django-sub-domains to support local development and testing of sub-domains.

Thank you, closing now.

**Comment by vaibhav-jain** [comment]
Yeah....I just modified windows hosts file and It worked like a charm..
