### ISSUE TITLE
pip install package is out of date.

### ISSUE THREAD

**Issue by the3rdshed** [tkaemming/django-subdomains#46]
pip install package is out of date. Changes made on 11-01-2014 for Python3 imports are not included when doing a pip install django-subdomains

**Comment by XavierBloemen** [comment]
:+1:

**Comment by eyscode** [comment]
:+1:

**Comment by EduardoCavalcanti** [comment]
:thumbsup:

**Comment by PetrDlouhy** [comment]
:thumbsup:

**Comment by WouterVH** [comment]
I think this package rather needs a new maintainer.

**Comment by PetrDlouhy** [comment]
I can became the new maintainer, or at least clean up this repository a bit (pull some important PRs and make the PyPI package).

@tkaemming, can you give me access to this repository and PyPI (with username "petr.dlouhy")?

**Comment by EduardoCavalcanti** [comment]
@tkaemming Any news on the new release?

**Comment by tkaemming** [comment]
I've merged a few compatibility changes in to the master branch (as of 2f19f24f114d3ea977dcf8806ca2c95fce2abc34) including the one mentioned here.

This isn't on PyPI yet, but probably will be sometime this week or next when the Django 1.9 build is green (not sure how much effort that will require, I haven't been following Django development since ~1.5.)

**Comment by PetrDlouhy** [comment]
@tkaemming That one with "Apps not ready" error is easy, just some lazy imports. See PR #51 
I am leaving one failed test to you, because it needs rather knowledge of subdomains internals.

**Comment by tkaemming** [comment]
2.1.0rc0 is up on [PyPI](https://pypi.python.org/pypi/django-subdomains/2.1.0rc0) and also [tagged](https://github.com/tkaemming/django-subdomains/releases/tag/2.1.0rc0).

Let me know if you're using this and it works fine (or conversely, if it doesn't) and I'll promote it to 2.1.0 if everything appears to be operating normally.

**Comment by leonmu** [comment]
I need this update to, I'm running on Python3. ^_^

**Comment by bartmika** [comment]
👍

**Comment by rodolfomartinez** [comment]
+1

**Comment by tkaemming** [comment]
This is up on PyPI as [2.1.0](https://pypi.python.org/pypi/django-subdomains/2.1.0) now so that it becomes the version installed by `pip` when a qualified version isn't otherwise specified (the release candidate suffix prevents this.)
