### ISSUE TITLE
Model class error

### ISSUE THREAD

**Issue by KhaledElAnsari** [tkaemming/django-subdomains#53]
I keep getting this error 

RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded.

**Comment by bartmika** [comment]
To fix this problem, do the following:

In your ``settings.py`` file, go to the **INSTALLED_APPS** section and make sure it looks like this:

  ```python
  INSTALLED_APPS = (
      # ...
      'django.contrib.sites',
      # ...
  )

  SITE_ID = 1
  ```

**Comment by tkaemming** [comment]
The previous comment is correct here.
