### ISSUE TITLE
ModuleNotFoundError: No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by NataliaSirera** [tkaemming/django-subdomains#68]
Hi,

I just updated to django 2.0 and the import of reverse is broken

File "lib/python3.6/site-packages/subdomains/utils.py", line 8, in <module>
    from django.core.urlresolvers import reverse as simple_reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'

Now, reverse is in django.urls

**Comment by mikob** [comment]
There's a PR for this already: https://github.com/tkaemming/django-subdomains/pull/67
